source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'activerecord-jdbcsqlite3-adapter'

gem 'jruby-openssl'
gem 'json'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyrhino'

  gem 'uglifier', '>= 1.0.3'
end

group :torquebox do
  gem 'torquebox', '2.0.0.cr1'
  gem 'torquebox-rake-support', '2.0.0.cr1'
  gem 'activerecord-jdbc-adapter', :require => 'arjdbc'
  gem "jdbc-sqlite3"
  gem "jruby-openssl"
end

gem 'jquery-rails'
gem 'newrelic_rpm'

